import { resolve } from 'node:path';
import { Prisma, Role } from '@prisma/client';
import { Router } from 'express';
import PDFDocument from 'pdfkit';
import { z } from 'zod';
import { config } from '../../config.js';
import { prisma } from '../../db.js';
import { AppError } from '../../http/errors.js';
import { authenticate, requireRole } from '../../security/auth.js';
import { audit } from '../../shared/audit.js';
import { parseBusinessDate } from '../../shared/domain.js';
import { createXlsx, type XlsxSheet, type XlsxValue } from '../../shared/xlsx.js';

export const reportsRouter = Router();
reportsRouter.use(authenticate, requireRole(Role.ADMIN, Role.SENIOR_ASSISTANT));

type Period = 'day' | 'week' | 'month' | 'year' | 'custom';
type Locale = 'es' | 'en';

const labels = {
  es: {
    report: 'Reporte de ventas', period: 'Periodo', generated: 'Generado', generatedBy: 'Generado por', sales: 'Ventas', revenue: 'Ingresos', ticket: 'Ticket promedio', services: 'Servicios', payments: 'Medios de pago', users: 'Ventas por usuario', summary: 'Resumen', total: 'Total',
    kpis: 'Indicadores principales', dayBreakdown: 'Desglose por día', userBreakdown: 'Desglose por usuario', serviceBreakdown: 'Desglose por servicio', paymentBreakdown: 'Desglose por medio de pago', date: 'Fecha', user: 'Usuario', units: 'Unidades', operations: 'Operaciones', folio: 'Folio', saleTotal: 'Total de venta', serviceCount: 'Servicios distintos', servicesDetail: 'Detalle de servicios', paymentMethods: 'Medios de pago', paymentsDetail: 'Detalle de pagos', notes: 'Observaciones', quantity: 'Cantidad', service: 'Servicio', suggestedPrice: 'Precio unitario sugerido', effectivePrice: 'Precio unitario cobrado', unitDifference: 'Diferencia unitaria', subtotal: 'Subtotal', overrideReason: 'Motivo del cambio', paymentCode: 'Código del medio', paymentMethod: 'Medio de pago', reference: 'Referencia', amount: 'Importe', serviceLines: 'Líneas de servicio', priceDetail: 'Detalle de precios',
  },
  en: {
    report: 'Sales report', period: 'Period', generated: 'Generated', generatedBy: 'Generated by', sales: 'Sales', revenue: 'Revenue', ticket: 'Average ticket', services: 'Services', payments: 'Payment methods', users: 'Sales by user', summary: 'Summary', total: 'Total',
    kpis: 'Key indicators', dayBreakdown: 'Breakdown by day', userBreakdown: 'Breakdown by user', serviceBreakdown: 'Breakdown by service', paymentBreakdown: 'Breakdown by payment method', date: 'Date', user: 'User', units: 'Units', operations: 'Operations', folio: 'Folio', saleTotal: 'Sale total', serviceCount: 'Distinct services', servicesDetail: 'Service details', paymentMethods: 'Payment methods', paymentsDetail: 'Payment details', notes: 'Notes', quantity: 'Quantity', service: 'Service', suggestedPrice: 'Suggested unit price', effectivePrice: 'Charged unit price', unitDifference: 'Unit difference', subtotal: 'Subtotal', overrideReason: 'Price change reason', paymentCode: 'Method code', paymentMethod: 'Payment method', reference: 'Reference', amount: 'Amount', serviceLines: 'Service lines', priceDetail: 'Price details',
  },
};

function addDays(date: Date, days: number) { const result = new Date(date); result.setUTCDate(result.getUTCDate() + days); return result; }
function lastDay(year: number, month: number) { return new Date(Date.UTC(year, month, 0)); }

function resolveRange(query: Record<string, unknown>, role: Role) {
  const period = (typeof query.period === 'string' ? query.period : query.from && query.to ? 'custom' : 'day') as Period;
  if (!['day', 'week', 'month', 'year', 'custom'].includes(period)) throw new AppError(422, 'INVALID_PERIOD', 'Periodo inválido');
  if (role === Role.SENIOR_ASSISTANT && !['day', 'month'].includes(period)) throw new AppError(403, 'SENIOR_PERIOD_FORBIDDEN', 'El asistente senior solo puede consultar día o mes');
  if (period === 'custom') {
    if (typeof query.from !== 'string' || typeof query.to !== 'string') throw new AppError(422, 'RANGE_REQUIRED', 'Debes indicar fecha inicial y final');
    const from = parseBusinessDate(query.from); const to = parseBusinessDate(query.to);
    if (from > to || addDays(from, 366 * 5) < to) throw new AppError(422, 'INVALID_RANGE', 'El rango debe ser válido y no superar cinco años');
    return { period, from, to };
  }
  const anchorValue = typeof query.anchor === 'string' ? query.anchor : new Date().toISOString().slice(0, 10);
  const anchor = parseBusinessDate(anchorValue);
  if (period === 'day') return { period, from: anchor, to: anchor };
  if (period === 'week') { const day = anchor.getUTCDay() || 7; const from = addDays(anchor, 1 - day); return { period, from, to: addDays(from, 6) }; }
  if (period === 'month') return { period, from: new Date(Date.UTC(anchor.getUTCFullYear(), anchor.getUTCMonth(), 1)), to: lastDay(anchor.getUTCFullYear(), anchor.getUTCMonth() + 1) };
  return { period, from: new Date(Date.UTC(anchor.getUTCFullYear(), 0, 1)), to: new Date(Date.UTC(anchor.getUTCFullYear(), 11, 31)) };
}

function addGroup(map: Map<string, { name: string; total: Prisma.Decimal; count: number }>, key: string, name: string, amount: Prisma.Decimal, count = 1) {
  const current = map.get(key) ?? { name, total: new Prisma.Decimal(0), count: 0 };
  current.total = current.total.add(amount); current.count += count; map.set(key, current);
}

async function buildReport(query: Record<string, unknown>, role: Role) {
  const range = resolveRange(query, role);
  const sales = await prisma.sale.findMany({
    where: { status: 'POSTED', businessDate: { gte: range.from, lte: range.to } },
    include: { items: true, payments: true, createdBy: { select: { id: true, name: true } } },
    orderBy: [{ businessDate: 'asc' }, { createdAt: 'asc' }],
  });
  let revenue = new Prisma.Decimal(0); let units = 0;
  const byService = new Map<string, { name: string; total: Prisma.Decimal; count: number }>();
  const byPayment = new Map<string, { name: string; total: Prisma.Decimal; count: number }>();
  const byUser = new Map<string, { name: string; total: Prisma.Decimal; count: number }>();
  const byDay = new Map<string, { name: string; total: Prisma.Decimal; count: number }>();
  for (const sale of sales) {
    revenue = revenue.add(sale.totalAmount);
    addGroup(byUser, sale.createdBy.id, sale.createdBy.name, sale.totalAmount);
    const day = sale.businessDate.toISOString().slice(0, 10); addGroup(byDay, day, day, sale.totalAmount);
    for (const item of sale.items) { units += item.quantity; addGroup(byService, item.serviceId, item.serviceNameSnapshot, item.lineTotal, item.quantity); }
    for (const payment of sale.payments) addGroup(byPayment, payment.paymentMethodId, payment.paymentMethodNameSnapshot, payment.amount);
  }
  const serialize = (map: typeof byService) => [...map.entries()].map(([id, value]) => ({ id, name: value.name, total: value.total.toFixed(2), count: value.count })).sort((a, b) => Number(b.total) - Number(a.total));
  return {
    period: range.period,
    from: range.from.toISOString().slice(0, 10),
    to: range.to.toISOString().slice(0, 10),
    currency: 'EUR',
    summary: { salesCount: sales.length, serviceUnits: units, grossRevenue: revenue.toFixed(2), averageTicket: sales.length ? revenue.div(sales.length).toDecimalPlaces(2).toFixed(2) : '0.00' },
    byDay: serialize(byDay), byService: serialize(byService), byPayment: serialize(byPayment), byUser: serialize(byUser),
    sales: sales.map((sale) => ({
      id: sale.id,
      folio: sale.folio,
      businessDate: sale.businessDate.toISOString().slice(0, 10),
      author: sale.createdBy.name,
      authorId: sale.createdBy.id,
      notes: sale.notes,
      total: sale.totalAmount.toFixed(2),
      items: sale.items.map((item) => ({
        id: item.id,
        serviceId: item.serviceId,
        name: item.serviceNameSnapshot,
        quantity: item.quantity,
        suggestedUnitPrice: item.suggestedUnitPriceSnapshot.toFixed(2),
        effectiveUnitPrice: item.effectiveUnitPrice.toFixed(2),
        unitDifference: item.effectiveUnitPrice.sub(item.suggestedUnitPriceSnapshot).toFixed(2),
        lineTotal: item.lineTotal.toFixed(2),
        priceOverrideReason: item.priceOverrideReason,
        position: item.position,
      })).sort((a, b) => a.position - b.position),
      payments: sale.payments.map((payment) => ({
        id: payment.id,
        paymentMethodId: payment.paymentMethodId,
        code: payment.paymentMethodCodeSnapshot,
        name: payment.paymentMethodNameSnapshot,
        amount: payment.amount.toFixed(2),
        reference: payment.reference,
        position: payment.position,
      })).sort((a, b) => a.position - b.position),
    })),
  };
}

reportsRouter.get('/sales', async (req, res) => {
  res.json({ data: await buildReport(req.query, req.auth!.role) });
});

reportsRouter.get('/sales/export', async (req, res) => {
  const format = z.enum(['pdf', 'xlsx']).parse(req.query.format);
  const report = await buildReport(req.query, req.auth!.role);
  const user = await prisma.user.findUniqueOrThrow({ where: { id: req.auth!.userId } });
  const locale: Locale = user.preferredLocale === 'EN' ? 'en' : 'es';
  const text = labels[locale];
  const filename = `reporte-ventas-${report.from}_${report.to}.${format}`;
  await audit(prisma, { actorUserId: user.id, action: 'REPORT_EXPORTED', entityType: 'REPORT', requestId: req.requestId, metadata: { format, period: report.period, from: report.from, to: report.to } });
  if (format === 'pdf') {
    res.setHeader('content-type', 'application/pdf'); res.setHeader('content-disposition', `attachment; filename="${filename}"`);
    const doc = new PDFDocument({ size: 'A4', margin: 48, info: { Title: `${text.report} - ${config.APP_BUSINESS_NAME}`, Author: config.APP_BUSINESS_NAME } });
    doc.pipe(res);
    try { doc.image(resolve(process.cwd(), 'logos/IMG-20260714-WA0010.jpg'), 48, 40, { fit: [64, 64] }); } catch { /* text remains available */ }
    doc.fillColor('#b76f3c').fontSize(20).text(config.APP_BUSINESS_NAME, 126, 50);
    doc.fillColor('#22201e').fontSize(15).text(text.report, 126, 78);
    doc.moveDown(3).fontSize(10).fillColor('#55504b').text(`${text.period}: ${report.from} — ${report.to}`);
    doc.text(`${text.generated}: ${new Intl.DateTimeFormat(locale, { timeZone: config.APP_TIMEZONE, dateStyle: 'medium', timeStyle: 'short' }).format(new Date())}`);
    doc.moveDown().fontSize(12).fillColor('#22201e');
    doc.text(`${text.sales}: ${report.summary.salesCount}`);
    doc.text(`${text.services}: ${report.summary.serviceUnits}`);
    doc.text(`${text.revenue}: ${report.summary.grossRevenue} EUR`);
    doc.text(`${text.ticket}: ${report.summary.averageTicket} EUR`);
    const section = (title: string, rows: Array<{ name: string; total: string; count: number }>) => {
      doc.moveDown().fontSize(13).fillColor('#b76f3c').text(title);
      doc.fontSize(9).fillColor('#22201e');
      rows.slice(0, 30).forEach((row) => doc.text(`${row.name}  ·  ${row.count}  ·  ${row.total} EUR`));
      doc.font('Helvetica-Bold').text(`${text.total}: ${report.summary.grossRevenue} EUR`).font('Helvetica');
    };
    section(text.services, report.byService); section(text.payments, report.byPayment); section(text.users, report.byUser);
    doc.end(); return;
  }
  const summaryName = locale === 'es' ? 'Resumen' : 'Summary';
  const asDate = (value: string) => new Date(`${value}T00:00:00Z`);
  const summaryRows: XlsxValue[][] = [
    [config.APP_BUSINESS_NAME],
    [text.report],
    [text.period, asDate(report.from), asDate(report.to)],
    [text.generated, new Intl.DateTimeFormat(locale, { timeZone: config.APP_TIMEZONE, dateStyle: 'medium', timeStyle: 'short' }).format(new Date())],
    [text.generatedBy, user.name],
    [],
    [text.kpis],
    [locale === 'es' ? 'Indicador' : 'Indicator', locale === 'es' ? 'Valor' : 'Value'],
    [text.sales, { value: report.summary.salesCount, style: 'integer' }],
    [text.services, { value: report.summary.serviceUnits, style: 'integer' }],
    [text.revenue, { value: Number(report.summary.grossRevenue), style: 'currency' }],
    [text.ticket, { value: Number(report.summary.averageTicket), style: 'currency' }],
    [],
  ];
  const summaryHeaderRows = [7];
  const summarySectionRows = [6];
  const appendBreakdown = (title: string, dimension: string, countLabel: string, rows: Array<{ name: string; count: number; total: string }>, dateDimension = false) => {
    summarySectionRows.push(summaryRows.length);
    summaryRows.push([title]);
    summaryHeaderRows.push(summaryRows.length);
    summaryRows.push([dimension, countLabel, text.revenue]);
    rows.forEach((row) => summaryRows.push([dateDimension ? { value: asDate(row.name), style: 'date' } : row.name, { value: row.count, style: 'integer' }, { value: Number(row.total), style: 'currency' }]));
    summaryRows.push([text.total, { value: rows.reduce((total, row) => total + row.count, 0), style: 'integer' }, { value: Number(report.summary.grossRevenue), style: 'totalCurrency' }], []);
  };
  appendBreakdown(text.dayBreakdown, text.date, text.sales, report.byDay, true);
  appendBreakdown(text.userBreakdown, text.user, text.sales, report.byUser);
  appendBreakdown(text.serviceBreakdown, text.service, text.units, report.byService);
  appendBreakdown(text.paymentBreakdown, text.paymentMethod, text.operations, report.byPayment);

  const salesRows: XlsxValue[][] = [[text.folio, text.date, text.user, text.serviceCount, text.units, text.servicesDetail, text.paymentMethods, text.paymentsDetail, text.notes, `${text.saleTotal} (EUR)`]];
  const serviceRows: XlsxValue[][] = [[text.folio, text.date, text.user, text.service, text.quantity, text.suggestedPrice, text.effectivePrice, text.unitDifference, text.subtotal, text.overrideReason, text.paymentMethods, text.paymentsDetail, text.saleTotal]];
  const paymentRows: XlsxValue[][] = [[text.folio, text.date, text.user, text.paymentCode, text.paymentMethod, text.reference, text.amount, text.saleTotal, text.servicesDetail, text.priceDetail]];
  for (const sale of report.sales) {
    const serviceNames = sale.items.map((item) => item.name).join(' | ');
    const serviceDetails = sale.items.map((item) => `${item.name} ×${item.quantity} @ ${item.effectiveUnitPrice} EUR`).join(' | ');
    const paymentMethods = [...new Set(sale.payments.map((payment) => payment.name))].join(' | ');
    const paymentDetails = sale.payments.map((payment) => `${payment.name}: ${payment.amount} EUR${payment.reference ? ` (${payment.reference})` : ''}`).join(' | ');
    salesRows.push([sale.folio, asDate(sale.businessDate), sale.author, sale.items.length, sale.items.reduce((total, item) => total + item.quantity, 0), serviceDetails, paymentMethods, paymentDetails, sale.notes ?? '', Number(sale.total)]);
    sale.items.forEach((item) => serviceRows.push([sale.folio, asDate(sale.businessDate), sale.author, item.name, item.quantity, Number(item.suggestedUnitPrice), Number(item.effectiveUnitPrice), Number(item.unitDifference), Number(item.lineTotal), item.priceOverrideReason ?? '', paymentMethods, paymentDetails, Number(sale.total)]));
    sale.payments.forEach((payment) => paymentRows.push([sale.folio, asDate(sale.businessDate), sale.author, payment.code, payment.name, payment.reference ?? '', Number(payment.amount), Number(sale.total), serviceNames, serviceDetails]));
  }
  salesRows.push([text.total, '', '', '', report.summary.serviceUnits, '', '', '', '', Number(report.summary.grossRevenue)]);
  serviceRows.push([text.total, '', '', '', report.summary.serviceUnits, '', '', '', Number(report.summary.grossRevenue), '', '', '', Number(report.summary.grossRevenue)]);
  paymentRows.push([text.total, '', '', '', '', '', Number(report.summary.grossRevenue), Number(report.summary.grossRevenue), '', '']);

  const sheets: XlsxSheet[] = [
    { name: summaryName, rows: summaryRows, titleRows: [0], sectionRows: summarySectionRows, headerRows: summaryHeaderRows, freezeRows: 8, merges: ['A1:D1'] },
    { name: locale === 'es' ? 'Ventas' : 'Sales', rows: salesRows, headerRows: [0], totalRows: [salesRows.length - 1], freezeRows: 1, autoFilter: { headerRow: 0, lastRow: Math.max(1, salesRows.length - 1) }, dateColumns: [1], integerColumns: [3, 4], currencyColumns: [9] },
    { name: locale === 'es' ? 'Servicios' : 'Services', rows: serviceRows, headerRows: [0], totalRows: [serviceRows.length - 1], freezeRows: 1, autoFilter: { headerRow: 0, lastRow: Math.max(1, serviceRows.length - 1) }, dateColumns: [1], integerColumns: [4], currencyColumns: [5, 6, 7, 8, 12] },
    { name: locale === 'es' ? 'Pagos' : 'Payments', rows: paymentRows, headerRows: [0], totalRows: [paymentRows.length - 1], freezeRows: 1, autoFilter: { headerRow: 0, lastRow: Math.max(1, paymentRows.length - 1) }, dateColumns: [1], currencyColumns: [6, 7] },
  ];
  const xlsx = await createXlsx(sheets, { title: `${text.report} - ${report.from} - ${report.to}`, creator: user.name, company: config.APP_BUSINESS_NAME });
  res.setHeader('content-type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); res.setHeader('content-disposition', `attachment; filename="${filename}"`);
  res.end(xlsx);
});
